[[libplist]]
arch = "aarch64"
git-tree-sha1 = "1304513cbd4f7d8b866af059088cc0435830c545"
os = "macos"

    [[libplist.download]]
    sha256 = "f09260b493123dbf3e31c002f265c691de39dc09143f87b8aa06ea18a3aa6dbf"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.aarch64-apple-darwin.tar.gz"
[[libplist]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "feb2bb3ea1d35e1d59ec1a2e483a0ed737daf378"
libc = "glibc"
os = "linux"

    [[libplist.download]]
    sha256 = "d61701ce7b86638e02217b979bb60596e1d01f40a5a421151b0db8e56631aea5"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.aarch64-linux-gnu-cxx03.tar.gz"
[[libplist]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a481f94255b316308a49404fa94ece739e83f04"
libc = "glibc"
os = "linux"

    [[libplist.download]]
    sha256 = "b05248972c2dc2819efba4b8f7661988f51800a8390d0ab061189d45470c6b71"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libplist]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee086be39866b8344e51a5ed44ac8695ef2f5389"
libc = "musl"
os = "linux"

    [[libplist.download]]
    sha256 = "09e54d813b72f5a576778b54aa5c6c0341135110098b88ed5d9d13a2d294d12b"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.aarch64-linux-musl-cxx03.tar.gz"
[[libplist]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a7a6a4f72437931522312d5c6dfcd3366731b1b"
libc = "musl"
os = "linux"

    [[libplist.download]]
    sha256 = "c6194997eab0e936c2b86842536527c5f153a3060f4de98ce6bb109e62c313be"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.aarch64-linux-musl-cxx11.tar.gz"
[[libplist]]
arch = "aarch64"
git-tree-sha1 = "2481a837874a13c7762b0c64f673bf28e0318749"
os = "freebsd"

    [[libplist.download]]
    sha256 = "7180e5c14a2c44c58dbeafc06738ad84747e57a792d9e9498937ffce15e9ed68"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.aarch64-unknown-freebsd.tar.gz"
[[libplist]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "faf978adc02895e5bbb5c60fd0904be8af612364"
libc = "glibc"
os = "linux"

    [[libplist.download]]
    sha256 = "d9d3f735de23a65d958d450bf58f55901dd61de6b3837ec80da43ece6009bb93"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libplist]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bce2e8a76a4b46c1859983703b6994683026ff4"
libc = "glibc"
os = "linux"

    [[libplist.download]]
    sha256 = "cdf1c196d73b4765dbadef1f5109f88de26d197a6f992c0bca3dc2abf6aab935"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libplist]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0d9bc85911597850397c350f5b236b794e19c17"
libc = "musl"
os = "linux"

    [[libplist.download]]
    sha256 = "339c7b795b2bac863478dc4b80de43ed4616037574ee18fe97da2d692ae3429d"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libplist]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1b1d2ffeb5eb77668411bf1f93c7ad3439112cf"
libc = "musl"
os = "linux"

    [[libplist.download]]
    sha256 = "7370e6af1db6042941a8e4caa5093dd98ea01292bade9ffbec1438f6cf295eff"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libplist]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "347c5e2644068ce7e1c46d9480b45358411b7bfb"
libc = "glibc"
os = "linux"

    [[libplist.download]]
    sha256 = "39467072d93eb367e33de4a9fcd945c2c764c00b9e39fe2774100a253dcecb43"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libplist]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "758eecaa316fc94c3452bc45541d30ef3876423a"
libc = "glibc"
os = "linux"

    [[libplist.download]]
    sha256 = "76eed11082cf284c5b369d56a50027ec3b89015d2f8cf0f7cc3b7653fcc94372"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libplist]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cdb89bc82a0eccaea56025c65d1b8a55f79a5db"
libc = "musl"
os = "linux"

    [[libplist.download]]
    sha256 = "47b5c3b0b231a72773e190c059199248e51492a827051f334f648b7e4a77496a"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libplist]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a5056e2f1a63ce57d4a2e3c1cf8986110e8c5f4"
libc = "musl"
os = "linux"

    [[libplist.download]]
    sha256 = "5e32560972aca6dc7f2cbd97a7210c34f4ef5d5880b9ac76eab94b7f244dd7dd"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libplist]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91a6ca2d518fe03eb18539e046dcad18501b4be3"
libc = "glibc"
os = "linux"

    [[libplist.download]]
    sha256 = "b8c114c4738c595a3599cdbe0f1422f19b75949d983764f9ffbbc78efef63533"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.i686-linux-gnu-cxx03.tar.gz"
[[libplist]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13c412683a13bdb0bab5c5fdb9e2e20b30bf23b1"
libc = "glibc"
os = "linux"

    [[libplist.download]]
    sha256 = "a7214a3018f3ce2736730bcbe47e7b8bfeb738214904542a6a2a2664168d6013"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.i686-linux-gnu-cxx11.tar.gz"
[[libplist]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b10e14a456d57429d3947dbf105e58c4898a4d2"
libc = "musl"
os = "linux"

    [[libplist.download]]
    sha256 = "52355f7dc41d56f72039d2710e7095b85372e0c2e200257f5cdf1f0b612b1556"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.i686-linux-musl-cxx03.tar.gz"
[[libplist]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0194e5e194efd8542413fb12b7825c1afa393ae2"
libc = "musl"
os = "linux"

    [[libplist.download]]
    sha256 = "2cc73a0e3b49a8d68ac33023cb3a3613fa6ed692a17fbecb96963be748a11545"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.i686-linux-musl-cxx11.tar.gz"
[[libplist]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9d809058b920a1539d684c76619d1d95dc90455"
os = "windows"

    [[libplist.download]]
    sha256 = "017db3dcb99251ab1813f155ce11ecff47f3a23797a03355649d687892bd8d1d"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.i686-w64-mingw32-cxx03.tar.gz"
[[libplist]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45402c42b862b80063251e69ad3042e98de8ffec"
os = "windows"

    [[libplist.download]]
    sha256 = "82a13c434e69419ccae3d632aedf1e22ba9e19af9ebb423530e610e22e0e0d5e"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.i686-w64-mingw32-cxx11.tar.gz"
[[libplist]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be385f8eeb5c7dc15cecdc83651c3bf8a8ebf138"
libc = "glibc"
os = "linux"

    [[libplist.download]]
    sha256 = "84b7a4bc9576a507e7ae19da47ced24bd8fe5e23cdcb68ffe61d4c0b55fe5aaa"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libplist]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a2fe4f75c0e0b6c0263e3262b55ee6f82985325"
libc = "glibc"
os = "linux"

    [[libplist.download]]
    sha256 = "9b1868cf5c6494ef900d461dbe2d7e6aea7fb95ac3455b80e21f83bed085e5c3"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libplist]]
arch = "x86_64"
git-tree-sha1 = "efaafaeed27c70a8f36fbcc1317d4687f7ea9dc5"
os = "macos"

    [[libplist.download]]
    sha256 = "6e47c07f5525f51310728f386b045445ae0ce17566fc3efda924ffa027132ba0"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.x86_64-apple-darwin.tar.gz"
[[libplist]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74dd8386d3046d438a1af22efb131d9faf702f24"
libc = "glibc"
os = "linux"

    [[libplist.download]]
    sha256 = "4076a875501682b25aadd1d049c7f6dae88fecd4126441cb794f72cf47a288b6"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.x86_64-linux-gnu-cxx03.tar.gz"
[[libplist]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9000bf6448deb3b60f176d657ab63bf36d533620"
libc = "glibc"
os = "linux"

    [[libplist.download]]
    sha256 = "669a5de5c73adaf37d4226114a9c64ceb67ff7be312126a01a32ac00936533f2"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libplist]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b935644f7c1cda195242d09db72f94aeb5cd4f55"
libc = "musl"
os = "linux"

    [[libplist.download]]
    sha256 = "81cfa76d899c9ce6233af5f34739f62e0e8cf10300e5a6d6b268d305ccb0a67b"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.x86_64-linux-musl-cxx03.tar.gz"
[[libplist]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c207f1421ebb7f6b98a395bd91fdfb7702af771"
libc = "musl"
os = "linux"

    [[libplist.download]]
    sha256 = "8b3058b6b761e26aba68c1916c3c852d204b3f67f8a95ba3bc98b834e0464bf1"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.x86_64-linux-musl-cxx11.tar.gz"
[[libplist]]
arch = "x86_64"
git-tree-sha1 = "74a778fe57b2af97ce077df114733766ee76d223"
os = "freebsd"

    [[libplist.download]]
    sha256 = "5ea923934922edae5b15e6cc163bef3360a699ef4e702d792ab88e8f6acb4bab"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.x86_64-unknown-freebsd.tar.gz"
[[libplist]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "030c96548032595eaee24fa429dd37cb781360b4"
os = "windows"

    [[libplist.download]]
    sha256 = "4fad213f6d8d23a5a7401b00512ac7d73d11c68a9d9c6503e86d5a25ca0d65ce"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[libplist]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd555e071d57f25d5475ccf348685b8348e0a899"
os = "windows"

    [[libplist.download]]
    sha256 = "ad0366d4d81b25071e7def2c55223e2632955c57e00ba92655fa8e470e569008"
    url = "https://github.com/JuliaBinaryWrappers/libplist_jll.jl/releases/download/libplist-v2.6.0+0/libplist.v2.6.0.x86_64-w64-mingw32-cxx11.tar.gz"
