# Autogenerated wrapper script for libplist_jll for x86_64-w64-mingw32-cxx11
export libplist, plistutil

JLLWrappers.@generate_wrapper_header("libplist")
JLLWrappers.@declare_library_product(libplist, "libplist-2.0.dll")
JLLWrappers.@declare_executable_product(plistutil)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libplist,
        "bin\\libplist-2.0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        plistutil,
        "bin\\plistutil.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
